#!/bin/bash
SITE_ROOT=$(realpath $(dirname $(realpath $0))/..)
# pip="pip install "
cd $SITE_ROOT
_prepare() {
	# apt install -y python3 python3-pip parallel
	# $pip --upgrade pip
	which parallel
	if [ $? -ne 0 ]; then
		apt update
		apt install -y parallel
	fi
	which pip
	if [ $? -ne 0 ]; then
		apt update
		apt install -y python-pip
	fi
	pip install -r $SITE_ROOT/agents/requirements.txt
}
$@
